name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Show Swift version
        run: swift --version

      - name: Build (debug)
        run: swift build -v

      - name: Build (release)
        run: swift build -c release
